version: '3'
services:
  mysql:
    build: ./mysql
    env_file: ./mysql/.env_sample
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - est-data:/var/lib/mysql
    networks:
      - app-net

  django:
    build: ./django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./ranking_app:/code
    networks:
      - app-net
    tty: true
    depends_on:
      - mysql

networks:
  app-net:
    driver: bridge

volumes:
  est-data:
